version: '3'

services: 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: sc-client
    command: serve -s dist -l 3000
    restart: unless-stopped
    networks:
      - vc-network
  api:
    build: ./server
    container_name: sc-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3002
    volumes:
      - ./server/uploads:/usr/src/app/uploads
    networks:
      - vc-network
  nginx:
    image: nginx:stable-alpine
    container_name: sc-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - client
      - api
    networks:
      - vc-network

volumes:
  mongodb_api:

networks:
  sc-network:
    driver: bridge
